In [1]:
from hmmlearn.hmm import CategoricalHMM
import numpy as np
from hmm import new_hmm, generate_until_terminates, total_entropy, expected_length

In [2]:
model = new_hmm(random_fill=True)

In [3]:
X, Z = generate_until_terminates(model)

Initial state
1


In [4]:
X

array([], dtype=int64)

In [5]:
Z

array([1])

In [6]:
model.startprob_

array([0.50007251, 0.49992749])

In [7]:
model.transmat_

array([[0.33868268, 0.66131732],
       [0.        , 1.        ]])

In [8]:
model.emissionprob_

array([[0.40337273, 0.59662727, 0.        ],
       [0.        , 0.        , 1.        ]])

In [9]:
total_entropy(model)

/Users/miguel/git/markov-coding/hmm.py:86: RuntimeWarning: divide by zero encountered in log
  return - np.sum(np.nan_to_num(distr * np.log(distr)), axis = 1)
/Users/miguel/git/markov-coding/hmm.py:86: RuntimeWarning: invalid value encountered in multiply
  return - np.sum(np.nan_to_num(distr * np.log(distr)), axis = 1)


np.float64(1.6871510648525776)

In [10]:
expected_length(model)

np.float64(0.7561763375962953)